import MuiProvider from "@/components/Providers/MuiProviders"; // ⬅️ add this
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { CartProvider } from "../context/CartContext";
import { OrderProvider } from "../context/OrderContext";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <OrderProvider>
            <MuiProvider>{children}</MuiProvider>
          </OrderProvider>
        </CartProvider>
      </body>
    </html>
  );
}
