import { Customer, Order, OrderItem, Product, PromotionCode } from "./models";

export const DATA = {
  products: [
    {
      product_id: "P001",
      product_name: "iPhone 15 Pro Max",
      price: 1199.99,
      shop_id: "SHOP001",
      image: "https://example.com/images/iphone15promax.jpg",
      review: 4.5,
      instock_Quantity: 25,
      product_category: "Electronics",
    },
    {
      product_id: "P002",
      product_name: "Nike Air Max 270",
      price: 150.0,
      shop_id: "SHOP002",
      image: "https://example.com/images/nikeairmax270.jpg",
      review: 4.2,
      instock_Quantity: 50,
      product_category: "Footwear",
    },
    {
      product_id: "P003",
      product_name: 'Samsung 55" QLED TV',
      price: 899.99,
      shop_id: "SHOP001",
      image: "https://example.com/images/samsung55qled.jpg",
      review: 4.7,
      instock_Quantity: 15,
      product_category: "Electronics",
    },
    {
      product_id: "P004",
      product_name: "Levi's 501 Original Jeans",
      price: 89.5,
      shop_id: "SHOP003",
      image: "https://example.com/images/levis501.jpg",
      review: 4.3,
      instock_Quantity: 100,
      product_category: "Clothing",
    },
    {
      product_id: "P005",
      product_name: "KitchenAid Stand Mixer",
      price: 379.99,
      shop_id: "SHOP004",
      image: "https://example.com/images/kitchenaid_mixer.jpg",
      review: 4.8,
      instock_Quantity: 30,
      product_category: "Home & Kitchen",
    },
    {
      product_id: "P006",
      product_name: "The Great Gatsby Book",
      price: 12.99,
      shop_id: "SHOP005",
      image: "https://example.com/images/great_gatsby.jpg",
      review: 4.4,
      instock_Quantity: 200,
      product_category: "Books",
    },
    {
      product_id: "P007",
      product_name: "Wireless Bluetooth Headphones",
      price: 79.99,
      shop_id: "SHOP001",
      image: "https://example.com/images/bluetooth_headphones.jpg",
      review: 4.1,
      instock_Quantity: 75,
      product_category: "Electronics",
    },
    {
      product_id: "P008",
      product_name: "Organic Green Tea (50 bags)",
      price: 24.99,
      shop_id: "SHOP006",
      image: "https://example.com/images/green_tea.jpg",
      review: 4.6,
      instock_Quantity: 150,
      product_category: "Food & Beverages",
    },
  ] as Product[],

  customers: [
    {
      Cus_id: "C001",
      Cus_name: "John Smith",
      Address: "123 Main St, New York, NY 10001",
      Loyal_points: 1250,
      Promotion_code_type: "percentage",
    },
    {
      Cus_id: "C002",
      Cus_name: "Emily Johnson",
      Address: "456 Oak Ave, Los Angeles, CA 90210",
      Loyal_points: 2890,
      Promotion_code_type: "fixed",
    },
    {
      Cus_id: "C003",
      Cus_name: "Michael Brown",
      Address: "789 Pine Rd, Chicago, IL 60601",
      Loyal_points: 750,
      Promotion_code_type: "free_delivery",
    },
    {
      Cus_id: "C004",
      Cus_name: "Sarah Davis",
      Address: "321 Elm St, Houston, TX 77001",
      Loyal_points: 3200,
      Promotion_code_type: "percentage",
    },
    {
      Cus_id: "C005",
      Cus_name: "David Wilson",
      Address: "654 Maple Dr, Phoenix, AZ 85001",
      Loyal_points: 890,
      Promotion_code_type: "fixed",
    },
    {
      Cus_id: "C006",
      Cus_name: "Lisa Anderson",
      Address: "987 Cedar Ln, Philadelphia, PA 19101",
      Loyal_points: 1670,
      Promotion_code_type: "free_delivery",
    },
  ] as Customer[],

  promotion_codes: [
    {
      PromotionCode_id: "PROMO001",
      Name: "SAVE20",
      Promotion_code_type: "percentage",
      Start_date: "2024-01-01",
      End_date: "2024-12-31",
      Period: 365,
    },
    {
      PromotionCode_id: "PROMO002",
      Name: "HOLIDAY50",
      Promotion_code_type: "fixed",
      Start_date: "2024-11-01",
      End_date: "2024-12-31",
      Period: 61,
    },
    {
      PromotionCode_id: "PROMO003",
      Name: "FREESHIP",
      Promotion_code_type: "free_delivery",
      Start_date: "2024-06-01",
      End_date: "2024-08-31",
      Period: 92,
    },
    {
      PromotionCode_id: "PROMO004",
      Name: "SUMMER15",
      Promotion_code_type: "percentage",
      Start_date: "2024-06-15",
      End_date: "2024-09-15",
      Period: 92,
    },
    {
      PromotionCode_id: "PROMO005",
      Name: "WELCOME25",
      Promotion_code_type: "fixed",
      Start_date: "2024-01-01",
      End_date: "2024-12-31",
      Period: 365,
    },
  ] as PromotionCode[],
  orders: [
    {
      Order_id: "ORD001",
      Cus_id: "C001",
      total_price: 1289.98,
      coupon: "SAVE20",
      total_delivery_fees: 15.99,
      loyalty_points: 128,
    },
    {
      Order_id: "ORD002",
      Cus_id: "C002",
      total_price: 150.0,
      coupon: null,
      total_delivery_fees: 9.99,
      loyalty_points: 15,
    },
    {
      Order_id: "ORD003",
      Cus_id: "C003",
      total_price: 989.49,
      coupon: "FREESHIP",
      total_delivery_fees: 0.0,
      loyalty_points: 98,
    },
    {
      Order_id: "ORD004",
      Cus_id: "C004",
      total_price: 102.48,
      coupon: "SUMMER15",
      total_delivery_fees: 7.99,
      loyalty_points: 10,
    },
    {
      Order_id: "ORD005",
      Cus_id: "C001",
      total_price: 404.98,
      coupon: "WELCOME25",
      total_delivery_fees: 12.99,
      loyalty_points: 40,
    },
    {
      Order_id: "ORD006",
      Cus_id: "C005",
      total_price: 92.98,
      coupon: null,
      total_delivery_fees: 5.99,
      loyalty_points: 9,
    },
    {
      Order_id: "ORD007",
      Cus_id: "C006",
      total_price: 79.99,
      coupon: "FREESHIP",
      total_delivery_fees: 0.0,
      loyalty_points: 8,
    },
  ] as Order[],
  order_items: [
    {
      OrderItem_id: "OI001",
      Order_id: "ORD001",
      Product_id: "P001",
      Quantity: 1,
      SubTotal: 1199.99,
      Delivery_fee_type: "standard",
    },
    {
      OrderItem_id: "OI002",
      Order_id: "ORD001",
      Product_id: "P007",
      Quantity: 1,
      SubTotal: 79.99,
      Delivery_fee_type: "standard",
    },
    {
      OrderItem_id: "OI003",
      Order_id: "ORD002",
      Product_id: "P002",
      Quantity: 1,
      SubTotal: 150.0,
      Delivery_fee_type: "standard",
    },
    {
      OrderItem_id: "OI004",
      Order_id: "ORD003",
      Product_id: "P003",
      Quantity: 1,
      SubTotal: 899.99,
      Delivery_fee_type: "express",
    },
    {
      OrderItem_id: "OI005",
      Order_id: "ORD006",
      Product_id: "P008",
      Quantity: 2,
      SubTotal: 49.98,
      Delivery_fee_type: "standard",
    },
    {
      OrderItem_id: "OI006",
      Order_id: "ORD003",
      Product_id: "P004",
      Quantity: 1,
      SubTotal: 89.5,
      Delivery_fee_type: "standard",
    },
    {
      OrderItem_id: "OI007",
      Order_id: "ORD004",
      Product_id: "P006",
      Quantity: 1,
      SubTotal: 12.99,
      Delivery_fee_type: "standard",
    },
    {
      OrderItem_id: "OI008",
      Order_id: "ORD005",
      Product_id: "P005",
      Quantity: 1,
      SubTotal: 379.99,
      Delivery_fee_type: "express",
    },
    {
      OrderItem_id: "OI009",
      Order_id: "ORD005",
      Product_id: "P008",
      Quantity: 1,
      SubTotal: 24.99,
      Delivery_fee_type: "standard",
    },
    {
      OrderItem_id: "OI010",
      Order_id: "ORD007",
      Product_id: "P007",
      Quantity: 1,
      SubTotal: 79.99,
      Delivery_fee_type: "standard",
    },
  ] as OrderItem[],
};
